

CREATE TABLE play_by_play (
    Ddate TEXT,
    GameID TEXT,
    Drive TEXT,
    qtr TEXT,
    down TEXT,
    ttime TEXT,
    TimeUnder TEXT,
    TimeSecs TEXT,
    PlayTimeDiff TEXT,
    SideofField TEXT,
    yrdln TEXT,
    yrdline100 TEXT,
    ydstogo TEXT,
    ydsnet TEXT,
    GoalToGo TEXT,
    FirstDown TEXT,
    posteam TEXT,
    DefensiveTeam TEXT,
    descr TEXT,
    PlayAttempted TEXT,
    Yards_Gained TEXT,
    sp TEXT,
    Touchdown TEXT,
    ExPointResult TEXT,
    TwoPointConv TEXT,
    DefTwoPoint TEXT,
    Ssafety TEXT,
    Onsidekick TEXT,
    PuntResult TEXT,
    PlayType TEXT,
    Passer TEXT,
    Passer_ID TEXT,
    PassAttempt TEXT,
    PassOutcome TEXT,
    PassLength TEXT,
    AirYards TEXT,
    YardsAfterCatch TEXT,
    QBHit TEXT,
    PassLocation TEXT,
    InterceptionThrown TEXT,
    Interceptor TEXT,
    Rusher TEXT,
    Rusher_ID TEXT,
    RushAttempt TEXT,
    RunLocation TEXT,
    RunGap TEXT,
    Receiver TEXT,
    Receiver_ID TEXT,
    Reception TEXT,
    ReturnResult TEXT,
    Returner TEXT,
    BlockingPlayer TEXT,
    Tackler1 TEXT,
    Tackler2 TEXT,
    FieldGoalResult TEXT,
    FieldGoalDistance TEXT,
    Fumble TEXT,
    RecFumbTeam TEXT,
    RecFumbPlayer TEXT,
    Sack TEXT,
    Challenge_Replay TEXT,
    ChalReplayResult TEXT,
    Accepted_Penalty TEXT,
    PenalizedTeam TEXT,
    PenaltyType TEXT,
    PenalizedPlayer TEXT,
    Penalty_Yards TEXT,
    PosTeamScore TEXT,
    DefTeamScore TEXT,
    ScoreDiff TEXT,
    AbsScoreDiff TEXT,
    HomeTeam TEXT,
    AwayTeam TEXT,
    Timeout_Indicator TEXT,
    Timeout_Team TEXT,
    posteam_timeouts_pre TEXT,
    HomeTimeouts_Remaining_Pre TEXT,
    AwayTimeouts_Remaining_Pre TEXT,
    HomeTimeouts_Remaining_Post TEXT,
    AwayTimeouts_Remaining_Post TEXT,
    No_Score_Prob TEXT,
    Opp_Field_Goal_Prob TEXT,
    Opp_Safety_Prob TEXT,
    Opp_Touchdown_Prob TEXT,
    Field_Goal_Prob TEXT,
    Safety_Prob TEXT,
    Touchdown_Prob TEXT,
    ExPoint_Prob TEXT,
    TwoPoint_Prob TEXT,
    ExpPts TEXT,
    EPA TEXT,
    airEPA TEXT,
    yacEPA TEXT,
    Home_WP_pre TEXT,
    Away_WP_pre TEXT,
    Home_WP_post TEXT,
    Away_WP_post TEXT,
    Win_Prob TEXT,
    WPA TEXT,
    airWPA TEXT,
    yacWPA TEXT,
    Season TEXT
);


COPY play_by_play(
    Ddate, GameID, Drive, qtr, down, ttime, TimeUnder, TimeSecs, PlayTimeDiff, SideofField,
    yrdln, yrdline100, ydstogo, ydsnet, GoalToGo, FirstDown, posteam, DefensiveTeam, descr,
    PlayAttempted, Yards_Gained, sp, Touchdown, ExPointResult, TwoPointConv, DefTwoPoint, Ssafety,
    Onsidekick, PuntResult, PlayType, Passer, Passer_ID, PassAttempt, PassOutcome, PassLength,
    AirYards, YardsAfterCatch, QBHit, PassLocation, InterceptionThrown, Interceptor, Rusher,
    Rusher_ID, RushAttempt, RunLocation, RunGap, Receiver, Receiver_ID, Reception, ReturnResult,
    Returner, BlockingPlayer, Tackler1, Tackler2, FieldGoalResult, FieldGoalDistance, Fumble,
    RecFumbTeam, RecFumbPlayer, Sack, Challenge_Replay, ChalReplayResult, Accepted_Penalty,
    PenalizedTeam, PenaltyType, PenalizedPlayer, Penalty_Yards, PosTeamScore, DefTeamScore,
    ScoreDiff, AbsScoreDiff, HomeTeam, AwayTeam, Timeout_Indicator, Timeout_Team,
    posteam_timeouts_pre, HomeTimeouts_Remaining_Pre, AwayTimeouts_Remaining_Pre,
    HomeTimeouts_Remaining_Post, AwayTimeouts_Remaining_Post, No_Score_Prob, Opp_Field_Goal_Prob,
    Opp_Safety_Prob, Opp_Touchdown_Prob, Field_Goal_Prob, Safety_Prob, Touchdown_Prob,
    ExPoint_Prob, TwoPoint_Prob, ExpPts, EPA, airEPA, yacEPA, Home_WP_pre, Away_WP_pre,
    Home_WP_post, Away_WP_post, Win_Prob, WPA, airWPA, yacWPA, Season
)
FROM '/Users/spencerhoag/Documents/GitHub/rdb-with-cache/NFL Play by Play 2009-2016 (v3).csv'
WITH (FORMAT csv, HEADER true);
